name: npm
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run type-check

  publish_to_npm:
    name: Publish to npm if version has been updated
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

  publish_to_github:
    name: Publish to Github if version has been updated
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
